In [399]:
import pandas as pd
import requests
import bs4

statURL = 'https://liquipedia.net/valorant/VCT/2023/LOCK_IN_S%C3%A3o_Paulo/Statistics'

response = requests.get(statURL)
soup = bs4.BeautifulSoup(response.text, 'html.parser')
table = soup.find('table')

df=pd.read_html(str(table))
df=pd.DataFrame(df[0])
df

,Player,Team,Agents,Maps,K,D,A,KD,KDA,ACS/Map,K/Map,D/Map,A/Map
0,Shin,NaN,NaN,5,97,74,28,1.31,1.68,276,19.4,14.8,5.6
1,trexx,NaN,NaN,2,46,27,9,1.70,2.03,275,23.0,13.5,4.5
2,k1Ng,NaN,NaN,2,44,32,23,1.37,2.09,267,22.0,16.0,11.5
3,Twisten,NaN,NaN,5,99,73,16,1.35,1.57,263,19.8,14.6,3.2
4,Nivera,NaN,NaN,5,93,70,37,1.32,1.85,262,18.6,14.0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,zekken,NaN,NaN,2,15,32,11,0.46,0.81,119,7.5,16.0,5.5
158,soulcas,NaN,NaN,2,16,30,10,0.53,0.86,112,8.0,15.0,5.0
159,2ge,NaN,NaN,1,10,18,6,0.55,0.88,111,10.0,18.0,6.0
160,koldamenta,NaN,NaN,2,17,34,19,0.50,1.05,110,8.5,17.0,9.5
161,NagZ,NaN,NaN,2,14,33,3,0.42,0.51,106,7.0,16.5,1.5

In [397]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player   162 non-null    object
 1   Team     0 non-null      float64
 2   Agents   0 non-null      float64
 3   Maps     162 non-null    int64
 4   K        162 non-null    int64
 5   D        162 non-null    int64
 6   A        162 non-null    int64
 7   KD       162 non-null    float64
 8   KDA      162 non-null    float64
 9   ACS/Map  162 non-null    int64
 10  K/Map    162 non-null    float64
 11  D/Map    162 non-null    float64
 12  A/Map    162 non-null    float64
dtypes: float64(7), int64(5), object(1)
memory usage: 16.6+ KB

In [13]:
df.describe()

,Team,Agents,Maps,K,D,A,KD,KDA,ACS/Map,K/Map,D/Map,A/Map
count,0.0,0.0,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000
mean,NaN,NaN,4.814815,70.740741,70.790123,31.722222,0.929444,1.351111,190.339506,13.891975,15.042593,6.281481
std,NaN,NaN,3.861294,63.715941,55.761407,30.911866,0.244055,0.324988,38.020289,3.369391,1.600264,2.826081
min,NaN,NaN,1.000000,7.000000,13.000000,2.000000,0.420000,0.510000,106.000000,7.000000,9.300000,1.000000
25%,NaN,NaN,2.000000,26.250000,32.000000,11.000000,0.762500,1.162500,163.000000,11.500000,14.000000,4.025000
50%,NaN,NaN,3.000000,46.500000,52.500000,20.500000,0.930000,1.340000,190.500000,13.800000,15.000000,6.000000
75%,NaN,NaN,5.000000,92.500000,78.750000,44.500000,1.107500,1.530000,216.000000,16.000000,16.200000,8.000000
max,NaN,NaN,17.000000,312.000000,279.000000,163.000000,1.700000,2.390000,276.000000,23.000000,19.000000,14.000000

In [158]:
#Get each data through table rows
table_data = table.find_all('tr')

#separate columns through table data
headers = []
for td in table.find_all('th'):
    headers.append(td.text)

headers

['Player',
 'Team',
 'Agents',
 'Maps',
 'K',
 'D',
 'A',
 'KD',
 'KDA',
 'ACS/Map',
 'K/Map',
 'D/Map',
 'A/Map']

In [270]:
#data and compstat will be merged to create finalized table
data={'Player':[],
      'Country':[],
      'Team':[],
      'Agents':[]}

CompStat = []

#gets index numbers of rows
for i in range(1, len(table_data)):

    #data on Country, Team, and Agents
    null = []

    #data already available on table
    IncStat = []

    #gets stat values of each player
    #no values for country, team, and agents as they are shown as images
    for td in table_data[i].find_all('td'):

        #country is at the start of each player's name, replaced by whitespace, thus need for removal
        IncStat.append(td.get_text(strip=True))

        #gets data on Country, Team, and Agents
        for x in td.find_all('a'):
            null.append(x.get('title'))

    #removes Team duplicate
    del null[3]

    #removes null values
    del IncStat[1:3]

    #appends values for the columns
    data['Country'].append(null[0])
    data['Player'].append(null[1])
    data['Team'].append(null[2])
    data['Agents'].append(null[3:])
    CompStat.append(IncStat)

print(data)
print(CompStat)

{'Player': ['Shin', 'Trexx', 'K1Ng', 'Twisten', 'Nivera', 'Qw1', 'NAts', 'JessieVash', 'Derke', 'CHICHOO', 'Keloqz', 'Heat', 'Jamppi', 'QutionerX', 'MaKo', 'CNed', 'Meteor', 'ZmjjKK', 'BuZz', 'Ethan', 'Shyy', 'MOLSI', 'Leaf', 'CeNder', 'Cloud', 'Emman', 'GarnetS', 'Mwzera', 'Xeppaa', 'Ardiis', 'Less', 'Leo', 'Aspas', 'Mixwell', 'Frz', 'Tacolilla', 'Crashies', 'Jawgemo', 'Zeek', 'Cryocells', 'Foxz', 'Monyet', 'QRaxs', 'S0m', 'KiNgg', 'F0rsakeN', 'Reita', 'Cauanzin', 'Dgzin', 'Mojj', 'T3xture', 'Brave', 'Redgar', 'Boostio', 'ANGE1', 'Jinggg', 'Fit1nho', 'Lmemore', 'Chronicle', 'Shao', 'AAAAY', 'Yay', 'Zyppan', 'Alfajer', 'MrFaliN', 'Invy', 'Asuna', 'Bang', 'Murizzz', 'PANcada', 'SUYGETSU', 'Zellsis', 'Takej', 'Nobody', 'Nukkye', 'Stax', 'Jzz', 'TS', 'BcJ', 'Saadhak', 'Rb', 'Stellar', 'ScreaM', 'Yuicaw', 'WudiYuChEn', 'Hoody', 'EJAY', 'Boaster', 'Crws', 'Sushiboys', 'JitboyS', 'Wolfen', 'Derrek', 'Mazino', 'AYRIN', 'TenZ', 'Qck', 'Daveeys', 'FNS', 'Victor', 'C0M', 'Tehbotol', 'BerLIN', 'Xand', 'Dep', 'SugarZ3ro', 'Fl1pzjder', 'BORKUM', 'RgLM', 'Smoggy', 'Mazin', 'Sayf', 'Laz', 'Sacy', 'Tuyz', 'Zest', 'Bazzi', 'Vanity', 'Benkai', 'Axeddy', 'Jremy', 'Mindfreak (Indonesian player)', 'Haodong', 'Rhyme', 'ATA KAPTAN', 'TZH', 'Carpe', 'Sayaplayer', 'Anthem', 'Destrian', 'Sheydos', 'EKo', 'Xms', 'Suggest', 'SouhcNi', 'BONECOLD', 'Xnfri', 'AsLanM4shadoW', 'AvovA', 'Secret', 'Nozwerr', 'Xeta', 'Newzera', 'DubsteP', 'D4v41', 'Crow', 'Melser', 'TENNN', 'Munchkin', 'SkRossi', 'Dephh', 'Seoldam', 'Khalil', 'Turko', 'Boo', 'Ban', 'Starxo', 'Zekken', 'Soulcas', '2geMONSTAH', 'Koldamenta', 'NagZ'], 'Country': ['France', 'Russia', 'South Korea', 'Czechia', 'Belgium', 'Turkey', 'Russia', 'Philippines', 'Finland', 'China', 'France', 'Brazil', 'Finland', 'Turkey', 'South Korea', 'Turkey', 'South Korea', 'China', 'South Korea', 'United States', 'Chile', 'Poland', 'United States', 'Lithuania', 'Russia', 'Philippines', 'Thailand', 'Brazil', 'United States', 'Latvia', 'Brazil', 'Sweden', 'Brazil', 'Spain', 'Brazil', 'Chile', 'United States', 'Cambodia', 'Poland', 'United States', 'Thailand', 'Indonesia', 'Turkey', 'United States', 'Chile', 'Indonesia', 'Japan', 'Brazil', 'Brazil', 'Turkey', 'South Korea', 'Turkey', 'Russia', 'United States', 'Ukraine', 'Singapore', 'Spain', 'Indonesia', 'Russia', 'Non-representing', 'China', 'United States', 'Sweden', 'Turkey', 'Turkey', 'Philippines', 'United States', 'United States', 'Brazil', 'Brazil', 'Non-representing', 'United States', 'Japan', 'China', 'Lithuania', 'South Korea', 'Brazil', 'South Korea', 'United States', 'Argentina', 'South Korea', 'United States', 'Belgium', 'Taiwan', 'China', 'Finland', 'Philippines', 'United Kingdom', 'Thailand', 'Thailand', 'Thailand', 'Bulgaria', 'United States', 'Chile', 'Canada', 'Canada', 'Brazil', 'Colombia', 'Canada', 'United States', 'United States', 'Indonesia', 'Taiwan', 'Brazil', 'Japan', 'Japan', 'Indonesia', 'Philippines', 'Brazil', 'China', 'Brazil', 'Sweden', 'Japan', 'Brazil', 'Brazil', 'South Korea', 'South Korea', 'United States', 'Singapore', 'Brazil', 'Philippines', 'Indonesia', 'China', 'Norway', 'Turkey', 'China', 'South Korea', 'South Korea', 'Japan', 'Lithuania', 'Russia', 'South Korea', 'France', 'South Korea', 'Turkey', 'Finland', 'Japan', 'Turkey', 'Denmark', 'South Korea', 'Argentina', 'South Korea', 'France', 'Philippines', 'Malaysia', 'Japan', 'Chile', 'Japan', 'South Korea', 'India', 'United Kingdom', 'South Korea', 'Brazil', 'Turkey', 'Lithuania', 'United States', 'Poland', 'United States', 'United Kingdom', 'Philippines', 'Spain', 'Chile'], 'Team': ['Karmine Corp', 'KOI', 'Gen.G Esports', 'Team Vitality', 'Karmine Corp', 'FUT Esports', 'Team Liquid', 'Team Secret', 'Fnatic', 'EDward Gaming', 'Team Heretics', 'MIBR', 'Team Liquid', 'BBL Esports', 'DRX', 'Natus Vincere', 'Gen.G Esports', 'EDward Gaming', 'DRX', 'Evil Geniuses', 'LeviatÃ¡n', 'Team Vitality', 'Cloud9', 'Team Vitality', 'Giants', 'Rex Regum Qeon', 'Talon Esports', 'FURIA Esports', 'Cloud9', 'NRG', 'LOUD', 'Fnatic', 'LOUD', 'Team Heretics', 'MIBR', 'LeviatÃ¡n', 'NRG', 'Evil Geniuses', 'Team Heretics', '100 Thieves', 'Talon Esports', 'Global Esports', 'FUT Esports', 'NRG', 'LeviatÃ¡n', 'Paper Rex', 'DetonatioN FocusMe', 'LOUD', 'FURIA Esports', 'FUT Esports', 'Global Esports', 'BBL Esports', 'Team Liquid', 'Evil Geniuses', 'Natus Vincere', 'Paper Rex', 'Giants', 'Rex Regum Qeon', 'Fnatic', 'Natus Vincere', 'FunPlus Phoenix', 'Cloud9', 'Natus Vincere', 'Fnatic', 'FUT Esports', 'Team Secret', '100 Thieves', '100 Thieves', 'MIBR', 'Sentinels', 'Natus Vincere', 'Cloud9', 'DetonatioN FocusMe', 'EDward Gaming', 'Giants', 'DRX', 'MIBR', 'Gen.G Esports', 'Evil Geniuses', 'LOUD', 'DRX', '100 Thieves', 'Karmine Corp', 'FunPlus Phoenix', 'FunPlus Phoenix', 'Giants', 'Rex Regum Qeon', 'Fnatic', 'Talon Esports', 'Talon Esports', 'Talon Esports', 'KOI', '100 Thieves', 'LeviatÃ¡n', 'Global Esports', 'Sentinels', 'FURIA Esports', 'KRÃœ Esports', 'NRG', 'NRG', 'Evil Geniuses', 'Rex Regum Qeon', 'FunPlus Phoenix', 'KRÃœ Esports', 'ZETA DIVISION', 'ZETA DIVISION', 'Rex Regum Qeon', 'Team Secret', 'MIBR', 'EDward Gaming', 'FURIA Esports', 'Team Liquid', 'ZETA DIVISION', 'Sentinels', 'LOUD', 'DRX', 'Global Esports', 'Cloud9', 'Paper Rex', 'KRÃœ Esports', 'Team Secret', 'Paper Rex', 'EDward Gaming', 'Giants', 'FUT Esports', 'FunPlus Phoenix', 'T1', 'T1', 'DetonatioN FocusMe', 'Team Vitality', 'KOI', 'Gen.G Esports', 'Karmine Corp', 'DetonatioN FocusMe', 'BBL Esports', 'Team Vitality', 'DetonatioN FocusMe', 'BBL Esports', 'Team Heretics', 'Gen.G Esports', 'LeviatÃ¡n', 'T1', 'Karmine Corp', 'Team Secret', 'Paper Rex', 'ZETA DIVISION', 'KRÃœ Esports', 'ZETA DIVISION', 'T1', 'Global Esports', 'Sentinels', 'DetonatioN FocusMe', 'FURIA Esports', 'BBL Esports', 'Team Heretics', 'T1', 'KOI', 'Sentinels', 'Team Liquid', 'Rex Regum Qeon', 'KOI', 'KRÃœ Esports'], 'Agents': [['Fade', 'Raze', 'Viper'], ['Sova'], ['KAY/O', 'Viper'], ['Jett', 'Raze'], ['Omen', 'Astra'], ['Jett', 'Neon'], ['Cypher', 'Viper'], ['Fade', 'Sova'], ['Jett', 'Raze'], ['Killjoy', 'Viper'], ['Jett'], ['Raze', 'Neon'], ['Raze', 'Jett'], ['Jett', 'Yoru'], ['Viper', 'Omen', 'Astra'], ['Jett', 'Raze'], ['Raze', 'Jett'], ['Jett'], ['Jett', 'Raze', 'Killjoy'], ['Breach', 'Yoru', 'KAY/O'], ['Killjoy'], ['KAY/O', 'Raze', 'Breach'], ['Killjoy', 'Cypher', 'Viper'], ['Killjoy', 'Cypher'], ['Sova'], ['Reyna', 'KAY/O'], ['Jett', 'Neon', 'Raze'], ['Sova', 'Skye', 'Fade'], ['Skye', 'Sova'], ['Jett', 'Sage', 'Killjoy'], ['Viper', 'Killjoy'], ['Sova', 'Fade', 'Sage'], ['Jett'], ['KAY/O', 'Breach'], ['Killjoy', 'Cypher'], ['Jett', 'Raze'], ['Sova', 'Killjoy', 'Breach'], ['Jett', 'Raze'], ['KAY/O', 'Killjoy'], ['Omen', 'Raze', 'Jett'], ['Skye', 'KAY/O', 'Sova'], ['Astra', 'Omen'], ['KAY/O', 'Fade'], ['Omen', 'Viper', 'Harbor'], ['Viper', 'KAY/O', 'Breach'], ['Chamber', 'Jett'], ['Sova'], ['Skye', 'Breach'], ['Jett', 'Neon'], ['Killjoy', 'Viper'], ['Jett', 'Raze'], ['Astra', 'Omen'], ['Breach', 'Sova'], ['Killjoy'], ['Omen', 'Cypher', 'Sova'], ['Raze', 'Sage'], ['Jett', 'Raze'], ['Cypher', 'Sage'], ['Breach', 'Raze', 'KAY/O'], ['Fade', 'Omen', 'Sage'], ['Skye'], ['Sage', 'Chamber', 'Jett'], ['KAY/O'], ['Killjoy', 'Cypher'], ['Omen', 'Sova', 'Killjoy'], ['KAY/O', 'Breach', 'Killjoy'], ['KAY/O', 'Sage', 'Breach'], ['Astra', 'Viper', 'Omen'], ['KAY/O', 'Breach'], ['Omen', 'Viper'], ['Killjoy', 'Viper', 'Cypher'], ['Phoenix', 'Neon', 'Sage'], ['Viper'], ['KAY/O', 'Sova', 'Breach'], ['Breach', 'Sage'], ['Harbor', 'KAY/O', 'Breach'], ['Breach', 'Fade'], ['Astra', 'Brimstone'], ['Astra', 'Omen'], ['Raze', 'Killjoy', 'Viper'], ['Killjoy', 'Astra', 'KAY/O'], ['Killjoy', 'Cypher'], ['KAY/O', 'Skye'], ['Killjoy', 'Jett', 'Chamber'], ['Viper'], ['Killjoy'], ['Neon'], ['Astra', 'Omen', 'Brimstone'], ['Omen', 'Viper', 'Brimstone'], ['Killjoy', 'Astra'], ['Breach', 'KAY/O', 'Harbor'], ['Jett'], ['Sova', 'Fade', 'Breach'], ['Omen', 'Astra', 'Brimstone'], ['Killjoy', 'Viper'], ['Sage', 'Jett'], ['Cypher', 'Killjoy', 'Viper'], ['Killjoy', 'Raze'], ['Viper', 'Breach', 'Killjoy'], ['KAY/O', 'Skye', 'Killjoy'], ['KAY/O', 'Sova', 'Fade'], ['Omen', 'Fade'], ['Fade'], ['KAY/O', 'Neon'], ['Jett'], ['Omen', 'Astra'], ['Viper', 'Breach'], ['Viper', 'Brimstone', 'Harbor'], ['Omen', 'Brimstone'], ['Harbor', 'Raze', 'Fade'], ['KAY/O', 'Skye', 'Viper'], ['Killjoy', 'KAY/O'], ['Killjoy'], ['Skye'], ['Harbor', 'Brimstone', 'Astra'], ['Sova', 'Fade', 'KAY/O'], ['Breach', 'Skye', 'Fade'], ['Astra', 'Omen', 'Killjoy'], ['Killjoy', 'Sage'], ['Breach', 'Sova'], ['Sage', 'Raze', 'KAY/O'], ['Omen', 'Astra'], ['Astra', 'Viper', 'Omen'], ['Astra', 'Viper', 'Omen'], ['Sage', 'Breach', 'Astra'], ['Omen', 'Astra'], ['Sova'], ['Jett'], ['Killjoy'], ['Astra', 'Omen', 'Harbor'], ['Killjoy'], ['Skye', 'Neon'], ['Cypher', 'Killjoy'], ['KAY/O', 'Breach'], ['Sova'], ['Fade', 'Sova', 'Breach'], ['Astra', 'Raze'], ['Killjoy'], ['Astra', 'Omen'], ['KAY/O', 'Breach'], ['Sova', 'Skye', 'Breach'], ['KAY/O'], ['Breach', 'Harbor', 'Sova'], ['Killjoy', 'Astra', 'Cypher'], ['Skye', 'Fade'], ['KAY/O', 'Sova'], ['Omen'], ['KAY/O', 'Sova'], ['Astra', 'Viper'], ['KAY/O', 'Sova', 'Sage'], ['Killjoy', 'Astra'], ['Jett'], ['Killjoy', 'Omen', 'Astra'], ['Breach', 'KAY/O'], ['Cypher', 'Sova'], ['Killjoy'], ['Breach', 'Sage'], ['Raze', 'Breach'], ['Astra', 'Sage'], ['Astra'], ['Omen', 'Viper'], ['Killjoy', 'Jett']]}

In [273]:
stat = pd.DataFrame(CompStat)
stat.columns=['Player', 'Maps', 'K', 'D', 'A', 'KD', 'KDA', 'ACS/Map', 'K/Map', 'D/Map', 'A/Map']
playerinfo = pd.DataFrame(data)

finalstats = pd.merge(playerinfo, stat, how='right')
finalstats

,Player,Country,Team,Agents,Maps,K,D,A,KD,KDA,ACS/Map,K/Map,D/Map,A/Map
0,Shin,France,Karmine Corp,"[Fade, Raze, Viper]",5,97,74,28,1.31,1.68,276,19.4,14.8,5.6
1,trexx,NaN,NaN,NaN,2,46,27,9,1.7,2.03,275,23,13.5,4.5
2,k1Ng,NaN,NaN,NaN,2,44,32,23,1.37,2.09,267,22,16,11.5
3,Twisten,Czechia,Team Vitality,"[Jett, Raze]",5,99,73,16,1.35,1.57,263,19.8,14.6,3.2
4,Nivera,Belgium,Karmine Corp,"[Omen, Astra]",5,93,70,37,1.32,1.85,262,18.6,14,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,zekken,NaN,NaN,NaN,2,15,32,11,0.46,0.81,119,7.5,16,5.5
158,soulcas,NaN,NaN,NaN,2,16,30,10,0.53,0.86,112,8,15,5
159,2ge,NaN,NaN,NaN,1,10,18,6,0.55,0.88,111,10,18,6
160,koldamenta,NaN,NaN,NaN,2,17,34,19,0.5,1.05,110,8.5,17,9.5
161,NagZ,Chile,KRÃœ Esports,"[Killjoy, Jett]",2,14,33,3,0.42,0.51,106,7,16.5,1.5

In [275]:
#Maps Picked

map_table = soup.find('table',attrs={'class': 'table table-bordered'})
map_values = map_table.find_all('tr')

map_values

In [394]:
#Side Stats
side_table = soup.find('table',attrs={'class': 'wikitable wikitable-bordered wikitable-striped'})
side_values = side_table.find_all('tr')

side_values

final_data=[]
for i in range(len(side_values)):
    temp=[]
    for td in side_values[i].find_all(['td','th']):
        temp.append(td.text)
    final_data.append(temp)
side_pick = pd.DataFrame(final_data)

side_pick.columns = side_pick.iloc[0]
side_pick.drop(0,inplace=True)
side_pick.set_index(keys='Map',inplace=True)

#separating numbers and percentage values to their own columns
side_pick[['Atk Wins', 'Atk Win %']] = side_pick['Atk Wins'].apply(lambda x: pd.Series(str(x).split(' ')))
side_pick[['Def Wins', 'Def Win %']] = side_pick['Def Wins'].apply(lambda x: pd.Series(str(x).split(' ')))

#changing values  for quantitative processing
side_pick['Atk Win %'] = side_pick['Atk Win %'].str.replace(r"\(|\)|%", '', regex=True)
side_pick['Def Win %'] = side_pick['Def Win %'].str.replace(r"\(|\)|%", '', regex=True)
side_pick = side_pick[['Atk Wins', 'Atk Win %', 'Def Wins', 'Def Win %']].apply(pd.to_numeric)

side_pick.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Ascent to Split
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Atk Wins   7 non-null      int64
 1   Atk Win %  7 non-null      float64
 2   Def Wins   7 non-null      int64
 3   Def Win %  7 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 280.0+ bytes

In [296]:
#Maps Banned
map_banned_table = soup.find('h3', string='Maps Banned').next_sibling.next_sibling
map_banned_values = map_banned_table.find_all('tr')

map_banned_values

[<tr style="background-color:rgb(238, 238, 238)"><th style="text-align:left">Map</th><th style="text-align:center">Total</th><th style="text-align:center">Knockouts</th></tr>,
 <tr><th style="text-align:left;background-color:rgb(249, 249, 249)"><b><a href="/valorant/Ascent" title="Ascent">Ascent</a></b></th><th style="text-align:center">20<i>Ã—</i></th><td style="text-align:center">20<i>Ã—</i></td></tr>,
 <tr><th style="text-align:left;background-color:rgb(249, 249, 249)"><b><a href="/valorant/Fracture" title="Fracture">Fracture</a></b></th><th style="text-align:center">17<i>Ã—</i></th><td style="text-align:center">17<i>Ã—</i></td></tr>,
 <tr><th style="text-align:left;background-color:rgb(249, 249, 249)"><b><a href="/valorant/Haven" title="Haven">Haven</a></b></th><th style="text-align:center">16<i>Ã—</i></th><td style="text-align:center">16<i>Ã—</i></td></tr>,
 <tr><th style="text-align:left;background-color:rgb(249, 249, 249)"><b><a href="/valorant/Icebox" title="Icebox">Icebox</a></b></th><th style="text-align:center">15<i>Ã—</i></th><td style="text-align:center">15<i>Ã—</i></td></tr>,
 <tr><th style="text-align:left;background-color:rgb(249, 249, 249)"><b><a href="/valorant/Lotus" title="Lotus">Lotus</a></b></th><th style="text-align:center">18<i>Ã—</i></th><td style="text-align:center">18<i>Ã—</i></td></tr>,
 <tr><th style="text-align:left;background-color:rgb(249, 249, 249)"><b><a href="/valorant/Pearl" title="Pearl">Pearl</a></b></th><th style="text-align:center">11<i>Ã—</i></th><td style="text-align:center">11<i>Ã—</i></td></tr>,
 <tr><th style="text-align:left;background-color:rgb(249, 249, 249)"><b><a href="/valorant/Split" title="Split">Split</a></b></th><th style="text-align:center">21<i>Ã—</i></th><td style="text-align:center">21<i>Ã—</i></td></tr>]